# DO NOT EDIT THIS FILE
#
# Please edit /boot/bootenv.txt to set supported parameters
#
setenv rootdev "LABEL=rootfs"
setenv verbosity "7"
setenv load_addr "0x44500000"

test -n "${distro_bootpart}" || distro_bootpart=1

if test -e ${devtype} ${devnum}:${distro_bootpart} ${prefix}bootenv.txt; then
        load ${devtype} ${devnum}:${distro_bootpart} ${load_addr} ${prefix}bootenv.txt
        env import -t ${load_addr} ${filesize}
fi

part uuid nvme ${devnum}:${distro_bootpart} partuuid
setenv bootargs "root=${rootdev} rootwait console=ttyS0,115200 console=tty1 consoleblank=0 loglevel=${verbosity}"

echo "Boot script loaded from ${devtype} ${devnum}:${distro_bootpart}"

echo "load initrd: ${prefix}${initrd_image}"
load ${devtype} ${devnum}:${distro_bootpart} ${ramdisk_addr_r} ${prefix}${initrd_image}
setenv initrdsz ${filesize}

echo "load kernel: ${prefix}${kernel_image}"
load ${devtype} ${devnum}:${distro_bootpart} ${kernel_addr_r} ${prefix}${kernel_image}

echo "load device-tree: ${prefix}${fdtfile}"
load ${devtype} ${devnum}:${distro_bootpart} ${fdt_addr_r} ${prefix}${fdtfile}

echo "booting..."
booti ${kernel_addr_r} ${ramdisk_addr_r}:${initrdsz} ${fdt_addr_r}

# Recompile with:
# mkimage -C none -A riscv -T script -d /boot/boot.cmd /boot/boot.scr
